import { describe, it, expect, vi } from "vitest"
import { render, screen, fireEvent } from "@testing-library/react"
import { Radio } from "./radio"

/**
 * What these tests can and cannot prove.
 *
 * jsdom has no layout engine and no style resolution: it does not match
 * `:hover`, `:focus-visible`, `:has()` or `:checked` selectors, it does not
 * apply a stylesheet, and every `getBoundingClientRect` is zero. So the
 * interaction tests below assert **class presence only** — that the component
 * emits the right utility on the right element. They do NOT prove the rule was
 * generated by Tailwind, that it resolves to the right token, or that anything
 * is actually painted.
 *
 * Rendered proof lives outside this file:
 *  - hover/focus actually painting, the halo geometry (control + 8, centred),
 *    the 2px-gap/2px-ring focus shadow, and that no Interaction state shifts
 *    layout — all verified in a real browser against Storybook.
 *  - the label leading and control alignment across scripts — same.
 * Treat a green run here as "the contract is wired", not "it looks right".
 */

/** label ▸ input ▸ focusRing ▸ band ▸ [halo?, control ▸ dot] */
const parts = (input: HTMLElement) => {
  const root = input.closest("label") as HTMLElement
  const control = root.querySelector("[data-slot=control]") as HTMLElement
  const band = control.parentElement as HTMLElement
  const siblings = [...(input.parentElement?.children ?? [])] as HTMLElement[]
  const focusRing =
    siblings.find((el) => el.className.includes("peer-focus-visible:opacity-100")) ?? null
  return {
    root,
    band,
    control,
    focusRing,
    dot: control.firstElementChild as HTMLElement,
    halo: band.children.length > 1 ? (band.firstElementChild as HTMLElement) : null,
  }
}

const radio = () => screen.getByRole("radio")

describe("Radio", () => {
  it("renders a radio input", () => {
    render(<Radio aria-label="Option A" />)
    expect(radio()).toBeInTheDocument()
  })

  it("is unchecked by default and reflects defaultChecked", () => {
    const { rerender } = render(<Radio aria-label="Option A" />)
    expect(radio()).not.toBeChecked()

    rerender(<Radio aria-label="Option A" defaultChecked />)
    expect(radio()).toBeChecked()
  })

  it("renders with different sizes", () => {
    const { rerender } = render(<Radio size="sm" label="Small" />)
    expect(parts(radio()).control).toHaveClass("size-4")

    rerender(<Radio size="md" label="Medium" />)
    expect(parts(radio()).control).toHaveClass("size-5")

    rerender(<Radio size="lg" label="Large" />)
    expect(parts(radio()).control).toHaveClass("size-6")
  })

  it("sizes the hover halo to the control plus 8px", () => {
    // Geometry is asserted as the class Figma's "control + 8" maps to; the
    // rendered box was measured in a browser, not here.
    const cases = [
      ["sm", "size-4", "size-6"],
      ["md", "size-5", "size-7"],
      ["lg", "size-6", "size-8"],
    ] as const
    for (const [size, control, halo] of cases) {
      const { unmount } = render(<Radio size={size} label="Option" />)
      const p = parts(radio())
      expect(p.control).toHaveClass(control)
      expect(p.halo).toHaveClass(halo)
      unmount()
    }
  })

  it("paints the dot with the foreground token, not the brand primary", () => {
    // Figma's theme/primary for the dot is the strong neutral. The docs app has
    // repurposed `--primary` as the Fasla brand red, so `bg-primary` would
    // render the dot red there. Guarding the choice, not the colour.
    render(<Radio label="Option" defaultChecked />)
    const { dot } = parts(radio())
    expect(dot).toHaveClass("bg-foreground")
    expect(dot).not.toHaveClass("bg-primary")
  })

  it("lets the type ramp own the label leading", () => {
    // The ramp makes `text-sm` direction-aware (20px English, 24px Arabic). A
    // hardcoded leading or a fixed line height would override it and clip
    // Arabic, which is the defect this component set had in Figma.
    render(<Radio label="Option" description="Detail" size="sm" />)
    const label = screen.getByText("Option")
    const description = screen.getByText("Detail")
    for (const el of [label, description]) {
      expect(el).toHaveClass("text-sm")
      expect(el.className).not.toMatch(/\bleading-/)
      expect(el.className).not.toMatch(/\bh-\d/)
    }
  })

  it("puts hover and focus on the control for the default variant", () => {
    // Class presence only — jsdom matches neither :hover nor :focus-visible.
    render(<Radio label="Option" />)
    const { root, halo, focusRing } = parts(radio())
    expect(halo).not.toBeNull()
    expect(halo).toHaveClass("bg-accent", "group-hover:opacity-100")
    // A circular ring around the control, sized to it — Figma's ellipse node.
    expect(focusRing).not.toBeNull()
    const ring = focusRing!.firstElementChild as HTMLElement
    expect(ring).toHaveClass("rounded-full", "ring-2", "ring-ring", "ring-offset-2")
    expect(ring).toHaveClass("size-5") // matches the md control
    expect(root).not.toHaveClass("hover:bg-accent")
  })

  it("puts hover and focus on the card for the layout variant", () => {
    // Class presence only — see the note at the top of this file.
    render(<Radio variant="layout" label="Option" />)
    const { root, halo, focusRing } = parts(radio())
    expect(halo).toBeNull() // the card fills instead of showing a halo
    expect(root).toHaveClass("hover:bg-accent")
    // A rounded rectangle around the whole card — Figma's −1,−1 node.
    expect(focusRing).not.toBeNull()
    expect(focusRing).toHaveClass("-inset-[2px]", "ring-2", "ring-ring")
    expect(focusRing!.className).toMatch(/rounded-\[calc\(var\(--radius\)-1px\)\]/)
  })

  it("drives hover and focus without a has-[] utility", () => {
    // `:has()` resolves in a browser but is invisible to the pseudo-state
    // renderer the Storybook states grid uses, so a `has-[:hover]` or
    // `has-[:focus-visible]` here would make the grid silently stop matching the
    // component. Both are `peer`- or `group`-driven instead.
    //
    // `has-[:disabled]` is deliberately still allowed: `disabled` is a real
    // attribute, not a simulated pseudo-state, so it renders statically anyway.
    for (const variant of ["default", "layout"] as const) {
      const { unmount } = render(<Radio variant={variant} label="Option" />)
      const html = (radio().closest("label") as HTMLElement).outerHTML
      expect(html).not.toMatch(/has-\[:hover\]/)
      expect(html).not.toMatch(/has-\[:focus-visible\]/)
      expect(html).toMatch(/has-\[:disabled\]/)
      unmount()
    }
  })

  it("renders the layout variant with a border", () => {
    const { rerender } = render(<Radio label="Default" data-testid="radio" />)
    expect(screen.getByTestId("radio").closest("label")).not.toHaveClass("border")

    rerender(<Radio variant="layout" label="Layout" data-testid="radio" />)
    expect(screen.getByTestId("radio").closest("label")).toHaveClass("border")
  })

  it("defaults to the default variant when variant is omitted", () => {
    render(<Radio label="Option" data-testid="radio" />)
    expect(screen.getByTestId("radio").closest("label")).not.toHaveClass(
      "border"
    )
  })

  it("rejects null as a variant", () => {
    // @ts-expect-error `variant` is declared on RadioProps rather than
    // inherited from CVA's VariantProps, which widens every variant with
    // `| null` and shows a meaningless third option in the Storybook control.
    render(<Radio label="Option" variant={null} data-testid="radio" />)
    expect(screen.getByTestId("radio")).toBeInTheDocument()
  })

  it("associates the label so clicking it selects the radio", () => {
    render(<Radio label="Express delivery" />)
    fireEvent.click(screen.getByText("Express delivery"))
    expect(radio()).toBeChecked()
  })

  it("links the description via aria-describedby", () => {
    render(<Radio label="Express" description="Arrives tomorrow" />)
    expect(radio()).toHaveAccessibleDescription("Arrives tomorrow")
  })

  it("keeps the control and its decoration out of the accessibility tree", () => {
    render(<Radio label="Option" />)
    expect(parts(radio()).band).toHaveAttribute("aria-hidden", "true")
  })

  it("renders no text column when label and description are omitted", () => {
    render(<Radio aria-label="Bare" />)
    // input, focus ring, control band — and no text column.
    expect(radio().parentElement?.childElementCount).toBe(3)
    expect(screen.queryByText(/./)).toBeNull()
  })

  it("selects only one radio per name group", () => {
    render(
      <>
        <Radio name="plan" value="a" label="Plan A" />
        <Radio name="plan" value="b" label="Plan B" />
      </>
    )
    const radios = screen.getAllByRole("radio")
    const a = radios[0]!
    const b = radios[1]!

    fireEvent.click(a)
    expect(a).toBeChecked()
    expect(b).not.toBeChecked()

    fireEvent.click(b)
    expect(a).not.toBeChecked()
    expect(b).toBeChecked()
  })

  it("handles onChange", () => {
    const handleChange = vi.fn()
    render(<Radio label="Option" onChange={handleChange} />)

    fireEvent.click(radio())
    expect(handleChange).toHaveBeenCalled()
  })

  it("is disabled when disabled prop is true", () => {
    render(<Radio label="Option" disabled />)
    expect(radio()).toBeDisabled()
    expect(radio().closest("label")).toHaveClass(
      "has-[:disabled]:opacity-50",
      // also kills hover, so a disabled card cannot fill
      "has-[:disabled]:pointer-events-none"
    )
  })

  it("applies custom className to the root", () => {
    render(<Radio label="Option" className="custom-class" />)
    expect(radio().closest("label")).toHaveClass("custom-class")
  })

  it("forwards ref correctly", () => {
    const ref = vi.fn()
    render(<Radio aria-label="Option" ref={ref} />)
    expect(ref).toHaveBeenCalled()
  })
})
