import index from "../../../design/index-atoms.json"

/**
 * The Figma atoms the landing page lists, read from the committed index
 * (design/index-atoms.json, regenerated by the figma-index skill), so the
 * counts on the page are the ones Figma had when it was last measured.
 *
 * Only primary atoms count: parts and family members are pieces of them.
 */
type Entry = { name: string; role: string; variants: number; rtl: boolean; code?: string | null }

/** Figma layer names that read differently on the page. */
const DISPLAY: Record<string, string> = {
  Breadcrumbs: "Breadcrumb",
  "Pagination Variants": "Pagination",
  "Check Box": "Checkbox",
  "Default Input": "Input",
  "Side Bar Inside Item": "Sidebar Item",
  "Calendar View": "Calendar",
  "Select Input": "Select",
  Sonnar: "Sonner",
  Dropdown: "Dropdown Menu",
}

export type Atom = {
  /** The name on the page, also the key of its Arabic name in the messages. */
  name: string
  variants: number
  rtl: boolean
  /** The registry item that implements it, if any. */
  code: string | null
}

export const atoms: Atom[] = (Object.values(index.entries) as Entry[])
  .filter((entry) => entry.role === "primary")
  .map((entry) => ({
    name: DISPLAY[entry.name] ?? entry.name,
    variants: entry.variants,
    rtl: entry.rtl,
    code: entry.code ?? null,
  }))

export const atomCounts = {
  atoms: atoms.length,
  variants: atoms.reduce((sum, atom) => sum + atom.variants, 0),
  measured: index.$meta.measured,
}
