import * as React from "react"
import { describe, it, expect, vi } from "vitest"
import { render, screen, fireEvent } from "@testing-library/react"
import { Checkbox } from "./checkbox"

/**
 * What these tests can and cannot prove.
 *
 * jsdom has no layout engine and no style resolution: it does not match
 * `:hover`, `:focus-visible` or `:has()` selectors and does not apply a
 * stylesheet. So the styling tests below assert **class presence only** — that
 * the component emits the right utility on the right element. They do NOT
 * prove the rule was generated by Tailwind or that anything is painted.
 *
 * Rendered proof — box and glyph geometry, fills per state, focus rings, the
 * box aligned to the first label line in both scripts — was checked in a real
 * browser against Storybook. Treat a green run here as "the contract is
 * wired", not "it looks right".
 */

/** label ▸ input ▸ focusRing ▸ band ▸ control ▸ [check, minus] */
const parts = (input: HTMLElement) => {
  const root = input.closest("label") as HTMLElement
  const control = root.querySelector("[data-slot=control]") as HTMLElement
  const siblings = [...(input.parentElement?.children ?? [])] as HTMLElement[]
  return {
    root,
    control,
    band: control.parentElement as HTMLElement,
    focusRing:
      siblings.find((el) => el.className.includes("peer-focus-visible:opacity-100")) ?? null,
    check: control.querySelector("[data-slot=check]") as SVGElement,
    minus: control.querySelector("[data-slot=minus]") as SVGElement,
  }
}

const checkbox = () => screen.getByRole("checkbox") as HTMLInputElement

describe("Checkbox", () => {
  it("renders a checkbox input", () => {
    render(<Checkbox aria-label="Accept" />)
    expect(checkbox()).toBeInTheDocument()
  })

  it("is unchecked by default and reflects defaultChecked", () => {
    const { unmount } = render(<Checkbox aria-label="Accept" />)
    expect(checkbox()).not.toBeChecked()
    unmount()

    render(<Checkbox aria-label="Accept" defaultChecked />)
    expect(checkbox()).toBeChecked()
  })

  it("sizes the box and glyph per Figma: 16/20/24 with the glyph 4px smaller", () => {
    const cases = [
      ["sm", "size-4", "size-3"],
      ["md", "size-5", "size-4"],
      ["lg", "size-6", "size-5"],
    ] as const
    for (const [size, box, glyph] of cases) {
      const { unmount } = render(<Checkbox size={size} label="Option" />)
      const p = parts(checkbox())
      expect(p.control).toHaveClass(box)
      expect(p.check).toHaveClass(glyph)
      expect(p.minus).toHaveClass(glyph)
      unmount()
    }
  })

  it("defaults to md", () => {
    render(<Checkbox label="Option" />)
    expect(parts(checkbox()).control).toHaveClass("size-5")
  })

  it("falls back to md for an unknown size", () => {
    // @ts-expect-error an untyped caller passing a typo
    render(<Checkbox label="Option" size="xl" />)
    expect(parts(checkbox()).control).toHaveClass("size-5")
  })

  it("fills the box with primary when checked or indeterminate", () => {
    render(<Checkbox label="Option" />)
    const { control } = parts(checkbox())
    expect(control).toHaveClass("rounded-sm", "border-input", "text-primary-foreground")
    expect(control).toHaveClass(
      "group-has-[:checked]/checkbox:bg-primary",
      "group-has-[:indeterminate]/checkbox:bg-primary"
    )
  })

  it("shows the tick only when checked and not indeterminate", () => {
    // Without the `:not(:indeterminate)` a checked *and* indeterminate input
    // would paint both glyphs on top of each other.
    render(<Checkbox label="Option" />)
    const { check, minus } = parts(checkbox())
    expect(check).toHaveClass("group-has-[:checked:not(:indeterminate)]/checkbox:opacity-100")
    expect(minus).toHaveClass("group-has-[:indeterminate]/checkbox:opacity-100")
  })

  it("sets the indeterminate DOM property and keeps it in step with the prop", () => {
    const { rerender } = render(<Checkbox label="Select all" indeterminate />)
    expect(checkbox().indeterminate).toBe(true)

    rerender(<Checkbox label="Select all" indeterminate={false} />)
    expect(checkbox().indeterminate).toBe(false)
  })

  it("restores indeterminate when a click clears it but the prop stays true", () => {
    // A parent that ignores the click re-renders with the same prop value.
    const Parent = () => {
      const [, force] = React.useState(0)
      return <Checkbox label="Select all" indeterminate onChange={() => force((n) => n + 1)} />
    }
    render(<Parent />)
    fireEvent.click(checkbox())
    expect(checkbox().indeterminate).toBe(true)
  })

  it("is not indeterminate by default", () => {
    render(<Checkbox label="Option" />)
    expect(checkbox().indeterminate).toBe(false)
  })

  it("does not mirror the glyphs in RTL", () => {
    render(<Checkbox label="Option" />)
    const { check, minus } = parts(checkbox())
    for (const glyph of [check, minus]) {
      expect(glyph.getAttribute("class")).not.toMatch(/rtl:|scale-x|rotate/)
    }
  })

  it("uses logical properties only — no rtl: overrides", () => {
    for (const variant of ["default", "layout"] as const) {
      const { unmount } = render(<Checkbox variant={variant} label="Option" description="Detail" />)
      expect(parts(checkbox()).root.outerHTML).not.toMatch(/\brtl:|\bltr:|\bleft-|\bright-/)
      unmount()
    }
  })

  it("lets the type ramp own the label leading", () => {
    // The ramp makes `text-sm` direction-aware (20px English, 24px Arabic). A
    // hardcoded leading would override it and clip Arabic.
    render(<Checkbox label="Option" description="Detail" size="sm" />)
    for (const el of [screen.getByText("Option"), screen.getByText("Detail")]) {
      expect(el).toHaveClass("text-sm")
      expect(el.className).not.toMatch(/\bleading-/)
    }
    expect(screen.getByText("Option")).toHaveClass("font-medium", "text-foreground")
    expect(screen.getByText("Detail")).toHaveClass("text-muted-foreground")
  })

  it("rings the box for the default variant, with no hover fill", () => {
    render(<Checkbox label="Option" />)
    const { root, focusRing } = parts(checkbox())
    expect(focusRing).not.toBeNull()
    const ring = focusRing!.firstElementChild as HTMLElement
    expect(ring).toHaveClass("rounded-sm", "ring-2", "ring-ring", "ring-offset-2", "size-5")
    // Tailwind's default offset colour is white, which shows as a halo in Dark.
    expect(ring).toHaveClass("ring-offset-background")
    expect(root).not.toHaveClass("hover:bg-accent")
  })

  it("rings and fills the card for the layout variant", () => {
    render(<Checkbox variant="layout" label="Option" />)
    const { root, focusRing } = parts(checkbox())
    expect(root).toHaveClass("rounded-md", "border", "p-2", "hover:bg-accent")
    expect(focusRing).toHaveClass("-inset-[2px]", "ring-2", "ring-ring")
  })

  it("drives focus without a has-[] utility", () => {
    // `:has()` is invisible to the pseudo-state renderer behind the Storybook
    // states grid, so focus must be `peer`-driven.
    for (const variant of ["default", "layout"] as const) {
      const { unmount } = render(<Checkbox variant={variant} label="Option" />)
      const html = parts(checkbox()).root.outerHTML
      expect(html).not.toMatch(/has-\[:hover\]|has-\[:focus-visible\]/)
      unmount()
    }
  })

  it("falls back to the default variant for null", () => {
    // @ts-expect-error `variant` is declared on CheckboxProps, not widened with `| null`
    render(<Checkbox label="Option" variant={null} />)
    expect(parts(checkbox()).root).not.toHaveClass("border")
  })

  it("toggles when its label is clicked", () => {
    render(<Checkbox label="Accept terms" />)
    fireEvent.click(screen.getByText("Accept terms"))
    expect(checkbox()).toBeChecked()
  })

  it("is named by the label alone and described by the description", () => {
    render(<Checkbox label="Marketing emails" description="About new features" />)
    expect(checkbox()).toHaveAccessibleName("Marketing emails")
    expect(checkbox()).toHaveAccessibleDescription("About new features")
  })

  it("keeps a caller's aria-label and aria-describedby", () => {
    render(
      <>
        <p id="extra">Extra</p>
        <Checkbox aria-label="Custom" description="Detail" aria-describedby="extra" />
      </>
    )
    expect(checkbox()).toHaveAccessibleName("Custom")
    expect(checkbox()).toHaveAccessibleDescription("Detail Extra")
  })

  it("keeps the box and glyphs out of the accessibility tree", () => {
    render(<Checkbox label="Option" />)
    expect(parts(checkbox()).band).toHaveAttribute("aria-hidden", "true")
  })

  it("renders no text column without a label or description", () => {
    render(<Checkbox aria-label="Bare" />)
    // input, focus ring, box band — and no text column.
    expect(checkbox().parentElement?.childElementCount).toBe(3)
  })

  it("handles onChange", () => {
    const handleChange = vi.fn()
    render(<Checkbox label="Option" onChange={handleChange} />)
    fireEvent.click(checkbox())
    expect(handleChange).toHaveBeenCalled()
  })

  it("dims and blocks the whole component when disabled", () => {
    render(<Checkbox label="Option" disabled />)
    expect(checkbox()).toBeDisabled()
    expect(parts(checkbox()).root).toHaveClass(
      "has-[:disabled]:opacity-50",
      "has-[:disabled]:pointer-events-none"
    )
  })

  it("applies className to the root", () => {
    render(<Checkbox label="Option" className="custom-class" />)
    expect(parts(checkbox()).root).toHaveClass("custom-class")
  })

  it("forwards its ref to the input", () => {
    const ref = React.createRef<HTMLInputElement>()
    render(<Checkbox aria-label="Option" ref={ref} />)
    expect(ref.current).toBe(checkbox())
  })

  it("uses the given id and links the label to it", () => {
    render(<Checkbox id="terms" label="Terms" />)
    expect(checkbox()).toHaveAttribute("id", "terms")
    expect(parts(checkbox()).root).toHaveAttribute("for", "terms")
  })
})
